 drop table if exists State cascade ;
 
    create table State (
        id integer generated by default as identity (start with 1),
        population integer not null,
        capital varchar(255),
        name varchar(255) not null unique,
        region varchar(255),
        type varchar(255) not null check (type in ('State','Region','Union')),
        primary key (id)
    )